### ISSUE TITLE
Missing chapters' code

### ISSUE THREAD

**Issue by jlgerber** [PacktPublishing/Rust-Programming-By-Example#2]

**Comment by sdc-andy** [comment]
Where is the code for the MP3 player in chapters 5-7?

-Andy.

**Comment by 64kramsystem** [comment]
Closed by https://github.com/PacktPublishing/Rust-Programming-By-Example/pull/5, although this repository is very likely abandoned.

**Comment by 64kramsystem** [comment]
@sohamapackt Why is this being closed? There's a PR that fixes the problem. Closing the issue means intentionally keep the repository in a broken state.

**Comment by sohamapackt** [comment]
Hi,

I am closing this issue. 
In case the issue still persists, feel free to open it again.

Thanks!
